# Generated by Django 4.2.4 on 2023-08-25 13:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Coupon')),
                ('coupon_type', models.CharField(choices=[('FIX', 'Fixed'), ('PRC', 'Percent')], max_length=3, verbose_name='Discount type')),
                ('value', models.PositiveIntegerField(verbose_name='Discount value')),
                ('total_allowed_apply', models.PositiveIntegerField(verbose_name='Total allowed apply')),
                ('active', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField(verbose_name='Valid from')),
                ('end_datetime', models.DateTimeField(verbose_name='Valid to')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
